spring:
  profiles:
    active: local

---
spring:
  profiles: local

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
    username: iyoungman
    password: duddnjsgl912!

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  redis:
    host: 54.180.67.243
    port: 6379

server:
  port: 8092

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
spring:
  profiles: test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true