spring:
    profiles:
        include: ${spring.profiles.active}

    output:
        ansi:
            enabled: always

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
