spring:
    profiles:
        include: redis

    datasource:
        url: jdbc:mysql://database-first.cjwqe1jklwit.ap-northeast-2.rds.amazonaws.com:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
        username: iyoungman
        password: duddnjsgl912

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        hibernate:
            ddl-auto: update

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace