spring:
  profiles:
    active: dev

---
spring:
  profiles: local

  output:
    ansi:
      enabled: always

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
    username: iyoungman
    password: duddnjsgl912!

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  redis:
    host: 54.180.116.179
    port: 6379

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

---
spring:
  profiles: test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

---
spring:
  profiles: dev

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  datasource:
    url: jdbc:mysql://iyoungman-skuniv-mysql-1.chxhgtrfuigt.ap-northeast-2.rds.amazonaws.com:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: duddnjsgl912!

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

#  redis:
#    host: 54.180.116.179
#    port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    s3:
      bucket: iyoungman-skuniv-s3-1
      dirName: mop
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true