spring:
    profiles:
        include: ${spring.profiles.active}

    output:
        ansi:
            enabled: always

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true

        hibernate:
            ddl-auto: update

        open-in-view: true

    http:
        encoding:
            charset: utf-8
            enabled: true
            force: true


    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace