spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mop?useSSL=false&serverTimezone=Asia/Seoul
        username: iyoungman
        password: duddnjsgl912!

    redis:
        host: 54.180.67.243
        port: 6379